### PR TITLE
Newly created account is added to firestore database

### LINKED ISSUE #35: Creating an account adds to firebase authentication but not firestore database
**Describe the bug**
Creating an account adds to firebase authentication but not firestore database

**To Reproduce**
1. Create account on frontend
2. Look at firestore database
3. no account added 

**Expected behavior**
1. Create account on frontend
2. Look at firestore database
3. Account added 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by SanjanaJ23**
Closes #35 
Fixed firestore database issue

### CODE REVIEW

File: frontend/src/webapp/pages/SignUp.js [hunk 1]
```diff
@@ -22,18 +22,20 @@ export default function SignUp() {
...
-        const user = userCredential.user;
-        addDoc(collection(db, "users"), {
+      const res = await createUserWithEmailAndPassword(auth, email, password);
+      const user = res.user;
+      try {
+        await addDoc(collection(db, "users"), {
           uid: user.uid,
           name,
           email,
-        })
```
Comment (Amandaha29) [inline frontend/src/webapp/pages/SignUp.js:32]: get_user from bcapi

**Review by Amandaha29 — CHANGES_REQUESTED** [review]

**Review by Amandaha29 — CHANGES_REQUESTED** [review]
Lgtm

**Review by Amandaha29 — APPROVED** [review]
